apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector:  # which pods should be part of the service
    #directly put labels under selector, not matchLabels, because services can only match labels
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80  #external port 
      targetPort: 8080 #internal port
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer #options: ClusterIP, NodePort

  # run:
  # verify docker and minikube are running
  # kubectl apply -f=service.yaml

  # delete:
  # kubectl delete -f=service.yaml