apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tasks
  template:
    metadata:
      labels:
        app: app-tasks
    spec:
      containers:
      - name: tasks
        imagePullPolicy: Always
        image: pmssdtest/kub-demo-tasks:4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: AUTH_ADDRESS
            value: "auth-service.default"
          - name: TASKS_FOLDER
            value: tasks
