apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: LoadBalancer
  selector:
    app: app-users
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  #auth-api port not exposed, because it will only be called internally